In [1]:
import mne
import pandas as pd

In [2]:
# EEG 데이터 파일 경로
file_path = "C:/Users/windows/Desktop/4class_EEG-GPT/k3b.gdf"
eeg_d = mne.io.read_raw_gdf(file_path, preload=True)

Extracting EDF parameters from C:\Users\windows\Desktop\4class_EEG-GPT\k3b.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
#  1, #  2, #  3, #  4, #  5, #  6, #  7, #  8, #  9, # 10, # 11, # 12, # 13, # 14, # 15, # 16, # 17, # 18, # 19, # 20, # 21, # 22, # 23, # 24, # 25, # 26, # 27, # 28, # 29, # 30, # 31, # 32, # 33, # 34, # 35, # 36, # 37, # 38, # 39, # 40, # 41, # 42, # 43, # 44, # 45, # 46, # 47, # 48, # 49, # 50, # 51, # 52, # 53, # 54, # 55, # 56, # 57, # 58, # 59, # 60
Creating raw.info structure...
Reading 0 ... 986779  =      0.000 ...  3947.116 secs...

In [3]:
eeg_d

In [4]:
channel = eeg_d.ch_names
channel

['#  1',
 '#  2',
 '#  3',
 '#  4',
 '#  5',
 '#  6',
 '#  7',
 '#  8',
 '#  9',
 '# 10',
 '# 11',
 '# 12',
 '# 13',
 '# 14',
 '# 15',
 '# 16',
 '# 17',
 '# 18',
 '# 19',
 '# 20',
 '# 21',
 '# 22',
 '# 23',
 '# 24',
 '# 25',
 '# 26',
 '# 27',
 '# 28',
 '# 29',
 '# 30',
 '# 31',
 '# 32',
 '# 33',
 '# 34',
 '# 35',
 '# 36',
 '# 37',
 '# 38',
 '# 39',
 '# 40',
 '# 41',
 '# 42',
 '# 43',
 '# 44',
 '# 45',
 '# 46',
 '# 47',
 '# 48',
 '# 49',
 '# 50',
 '# 51',
 '# 52',
 '# 53',
 '# 54',
 '# 55',
 '# 56',
 '# 57',
 '# 58',
 '# 59',
 '# 60']

In [5]:
# 데이터를 DataFrame으로 변환
eeg_d = eeg_d.to_data_frame()

# eeg_d = eeg_d.T

eeg_d

# CSV 파일로 저장
csv_file_path = "eeg_data.csv"
eeg_d.to_csv(csv_file_path, index=False)

print("CSV 파일이 저장되었습니다:", csv_file_path)

CSV 파일이 저장되었습니다: eeg_data.csv

In [6]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 51,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,7.517344,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,11.928453,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,12.015903,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.385745,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.538458,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,6.699425,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,9.901658,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,11.035943,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,8.793093,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,-0.646421,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197

In [7]:
'''
eeg_d = eeg_d.drop(index=['time'])

eeg_d
'''

"\neeg_d = eeg_d.drop(index=['time'])\n\neeg_d\n"

HDR.TRIG / HDR.Classlabel 로드

In [8]:
import numpy as np

# CSV 파일 읽기
eeg_d = pd.read_csv('eeg_data.csv')
trig_df = pd.read_csv('Trig.csv', header=None)
label_df = pd.read_csv('Classlabel.csv', header=None)

In [9]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 51,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,7.517344,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,11.928453,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,12.015903,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.385745,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.538458,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,6.699425,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,9.901658,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,11.035943,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,8.793093,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,-0.646421,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197

In [10]:
trig_df

            0
0      2425.0
1      4985.0
2      7545.0
3     10105.0
4     12666.0
..        ...
355  970000.0
356  972000.0
357  975000.0
358  977000.0
359  980000.0

[360 rows x 1 columns]

In [11]:
# trigger dataframe에 index 컬럼 이름 지정
trig_df.columns = ['index']

In [12]:
trig_df

        index
0      2425.0
1      4985.0
2      7545.0
3     10105.0
4     12666.0
..        ...
355  970000.0
356  972000.0
357  975000.0
358  977000.0
359  980000.0

[360 rows x 1 columns]

In [13]:
label_df

       0
0    3.0
1    4.0
2    NaN
3    NaN
4    3.0
..   ...
355  NaN
356  NaN
357  NaN
358  NaN
359  NaN

[360 rows x 1 columns]

In [14]:
# label dataframe에 label 컬럼 이름 지정
label_df.columns = ['label']

In [15]:
label_df

     label
0      3.0
1      4.0
2      NaN
3      NaN
4      3.0
..     ...
355    NaN
356    NaN
357    NaN
358    NaN
359    NaN

[360 rows x 1 columns]

In [16]:
# eeg_d에 label 열 추가
eeg_d['label'] = 0

In [17]:
'''
# 결과를 저장할 배열 초기화
label = np.full((eeg_d.shape[0],), np.nan)  # 초기값을 NaN으로 설정
'''

'\n# 결과를 저장할 배열 초기화\nlabel = np.full((eeg_d.shape[0],), np.nan)  # 초기값을 NaN으로 설정\n'

In [18]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286,0
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928,0
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292,0
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115,0
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447,0
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015,0
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892,0
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595,0
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197,0

trig_df, label_df를 통해 eeg_d에 label 값 정하기

In [19]:
# 트리거 인덱스와 레이블 가져오기
trigger_indices = trig_df['index'].values
labels = label_df['label'].values

In [20]:
# 트리거 구간에 따라 레이블 지정
for i in range(len(trigger_indices) - 1):
    start_idx = trigger_indices[i]
    end_idx = trigger_indices[i + 1]
    label = labels[i]
    eeg_d.loc[start_idx:end_idx-1, 'label'] = label

In [21]:
# 마지막 트리거 이후 구간 레이블 지정
if len(trigger_indices) > 0:
    start_idx = trigger_indices[-1]
    label = labels[-1]
    eeg_d.loc[start_idx:, 'label'] = label

In [22]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286,0.0
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928,0.0
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292,0.0
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115,0.0
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447,NaN
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015,NaN
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892,NaN
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595,NaN
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197,NaN

In [23]:
eeg_d[4945:5045]

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
4945,19.780,-4.885547,-5.559501,-5.559030,-3.570363,-6.286321,-5.226025,-3.923409,-3.190051,-1.170646,...,2.765395,0.040494,0.034225,0.705872,2.341688,3.777710,1.545675,1.532160,2.920502,3.0
4946,19.784,-2.886524,-3.863272,-3.267515,-1.328343,-5.090934,-3.460425,-2.250967,-0.995626,1.676314,...,7.169408,2.610561,3.875613,4.593546,6.147564,7.550743,4.579489,4.513506,5.572385,3.0
4947,19.788,-1.393920,-2.766604,-1.449020,0.115002,-2.773159,-1.876197,-0.773217,0.409286,3.588870,...,7.134413,5.186997,7.008076,7.101800,7.625415,7.920253,6.574010,6.013453,6.142497,3.0
4948,19.792,-1.522746,-2.500975,-1.259812,-0.010351,-0.779325,-1.265454,-0.402982,0.286206,2.904475,...,4.402094,7.081904,8.799624,8.163811,7.215551,5.959584,7.506316,6.182689,5.082175,3.0
4949,19.796,-3.273002,-3.377550,-3.158896,-2.288186,-1.541271,-2.405506,-1.775406,-1.713092,-0.573753,...,1.610553,7.183815,8.445162,7.316589,5.355941,3.234756,7.218473,5.211318,3.134294,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5040,20.160,2.239860,3.240400,0.923083,0.419429,0.178810,-0.358595,0.193863,1.832210,0.704410,...,1.562098,-5.758877,-5.060148,-3.611379,-2.101234,-0.289422,-5.484824,-3.542619,-2.240737,4.0
5041,20.164,0.316356,1.422741,-1.112651,-1.690075,-0.117755,-2.272254,-2.008399,-0.557341,-1.330025,...,1.134079,-5.832125,-5.021680,-3.382272,-1.651555,-0.344723,-5.711532,-3.531028,-2.221302,4.0
5042,20.168,-0.998557,0.056650,-2.058689,-2.789596,-0.277445,-3.364187,-3.029738,-1.881201,-2.551936,...,1.300980,-4.529576,-3.980273,-2.401404,-0.649146,0.072547,-4.873476,-2.851763,-1.530257,4.0
5043,20.172,-1.158479,-0.558091,-1.785389,-2.495913,-0.592260,-3.486335,-2.780787,-2.016289,-2.223802,...,2.361604,-3.201549,-2.826208,-1.442014,0.259580,1.020204,-3.959002,-2.174817,-0.860808,4.0
5044,20.176,-0.385524,0.231206,-0.145590,-0.930797,-0.473634,-2.061270,-0.929610,-0.761474,-0.089364,...,2.617338,-1.803458,-1.422095,-0.716506,0.697549,1.475180,-2.537618,-1.375000,-0.208634,4.0

In [24]:
print(eeg_d['label'].value_counts())  # 각 레이블의 개수 출력

label
1.0    126921
2.0    125360
4.0    125241
3.0    124652
0.0      2425
Name: count, dtype: int64

In [26]:
# CSV 파일로 저장
csv_file_path = "eeg_data_labeled.csv"
eeg_d.to_csv(csv_file_path, index=False)

print("CSV 파일이 저장되었습니다:", csv_file_path)

CSV 파일이 저장되었습니다: eeg_data_labeled.csv

epoch로 자르기

In [27]:
# 샘플링 주파수
fs = 250
start_offset = 3 * fs
end_offset = 7 * fs

# Epochs를 저장할 리스트 초기화
epochs = []

trigger_indices = trig_df['index'].values.astype(int)  # 정수로 변환
labels = label_df['label'].values

# Epoch 추출
for idx, label in zip(trigger_indices, labels):
    start_idx = int(idx + start_offset)  # 정수로 변환
    end_idx = int(idx + end_offset)  # 정수로 변환
    
    if end_idx <= len(eeg_d):
        epoch = eeg_d.iloc[start_idx:end_idx].copy()
        epoch['label'] = label
        epochs.append(epoch)

# epochs 리스트를 단일 DataFrame으로 결합
epochs_df = pd.concat(epochs, ignore_index=True)

In [28]:
epochs[0]

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
3175,12.700,-3.348520,-0.250720,-2.482654,-1.851242,-2.175465,-0.987844,-1.392404,-0.524320,-0.083113,...,6.283760,4.919481,4.043227,4.352506,5.283337,5.994775,3.647183,3.511997,5.006592,3.0
3176,12.704,-3.615057,-0.941355,-3.589869,-2.098366,-4.178424,-3.049562,-3.090380,-1.478940,-0.667506,...,7.470905,5.362157,5.123103,5.829774,6.866582,7.578393,4.895352,5.547473,7.055971,3.0
3177,12.708,-3.428481,-1.134885,-4.175011,-2.005247,-3.297852,-3.190218,-3.645733,-2.190402,-1.164395,...,7.102110,5.530947,5.694640,6.371519,7.344365,7.590961,5.231593,6.639396,7.854992,3.0
3178,12.712,-2.926504,-0.781978,-3.947261,-1.704401,-1.107828,-2.090882,-3.358481,-2.673715,-1.867541,...,4.114056,4.871710,4.842830,4.875158,5.484756,5.034550,4.210133,5.494151,6.107945,3.0
3179,12.716,-3.219694,-1.427076,-4.115446,-2.574706,-0.473634,-1.879898,-4.105335,-4.270752,-3.961353,...,0.816430,3.180625,2.015370,1.242844,1.575828,1.201189,2.014375,2.137239,2.322316,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4170,16.680,-4.783375,-4.204794,-4.644526,-1.360577,-4.835431,-6.606673,-4.284070,-3.163033,-2.983199,...,-7.068261,-7.357605,-8.525092,-8.806878,-8.209372,-6.933076,-9.827940,-9.317529,-6.980871,3.0
4171,16.684,-5.933924,-6.003480,-5.972484,-2.549635,-8.106778,-9.064448,-6.109713,-4.558940,-4.298863,...,-9.948636,-11.325763,-13.124866,-14.009536,-12.963790,-10.645780,-13.957084,-14.271756,-11.211360,3.0
4172,16.688,-5.551888,-5.540527,-5.390845,-2.474424,-8.248217,-8.957105,-6.138438,-4.697029,-4.370740,...,-8.336164,-12.392643,-14.520735,-15.575106,-13.888911,-10.344139,-14.540412,-15.574646,-11.908883,3.0
4173,16.692,-5.951693,-5.286283,-5.310257,-3.470081,-7.650523,-8.857166,-6.636341,-5.798745,-5.445772,...,-5.590386,-11.580540,-13.943702,-14.768456,-12.600768,-8.478989,-12.861753,-14.332032,-10.613174,3.0
4174,16.696,-6.720207,-5.365971,-5.786780,-4.945659,-7.294645,-9.319849,-7.514054,-7.281707,-6.780186,...,-7.181322,-9.510474,-12.185127,-13.150381,-11.413335,-8.571995,-9.807562,-11.888534,-9.317466,3.0

In [29]:
epochs[359]

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
980750,3923.000,-4.032631,-6.534738,-4.833734,-5.303809,-6.710638,-6.862074,-5.627769,-6.303072,-5.845784,...,-5.738443,0.524571,-0.691187,-3.623312,-4.752466,-4.429452,2.646101,-0.918293,-3.113181,NaN
980751,3923.004,-3.708345,-6.842108,-4.644526,-5.719264,-7.696149,-6.710314,-5.324559,-6.255041,-6.717685,...,-1.625159,4.027760,3.216147,0.813266,-0.091731,0.165553,6.680996,3.748464,1.577284,NaN
980752,3923.008,-3.477346,-6.519559,-4.732122,-5.844616,-9.051226,-6.721418,-5.219233,-5.900811,-8.383359,...,3.322626,6.632859,6.464016,5.304735,4.840684,5.476957,10.089260,8.148616,6.807627,NaN
980753,3923.012,-2.104684,-5.320435,-3.758054,-4.437086,-8.987350,-5.895991,-4.290453,-4.606971,-8.902124,...,7.941995,8.470441,8.747417,8.908411,8.955715,10.217756,12.473516,11.755906,11.554240,NaN
980754,3923.016,-0.327774,-3.244736,-1.999123,-1.998084,-4.762430,-4.171107,-2.841429,-2.739758,-6.530179,...,9.586770,8.215664,8.686966,9.674491,10.096307,11.788806,12.111802,12.560359,13.057262,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981745,3926.980,18.494142,17.895518,17.173916,16.152963,11.457431,14.613845,14.783050,13.870026,10.645329,...,-0.483776,2.046866,2.122533,3.660409,1.650775,-0.296963,0.310243,0.590927,-0.685887,NaN
981746,3926.984,17.272516,15.736336,15.555139,15.447407,10.184480,13.225794,13.567019,12.519149,10.392196,...,-3.321081,-0.777979,-1.012677,0.116397,-1.501662,-3.569774,-2.677719,-2.698755,-4.108717,NaN
981747,3926.988,15.522260,13.413982,12.625925,12.739792,8.952592,10.701393,10.633861,8.913808,7.604614,...,-6.605247,-4.946774,-5.013436,-4.422803,-5.424642,-7.337779,-6.531757,-6.686247,-7.820922,NaN
981748,3926.992,15.357896,12.674016,10.558657,10.551495,9.500098,9.061642,8.546500,6.149013,5.670182,...,-8.363084,-7.873529,-7.868374,-7.451323,-7.961112,-9.479433,-8.859973,-9.243343,-10.043062,NaN
981749,3926.996,15.633317,11.546991,9.101057,9.047265,9.559411,7.954903,7.537928,5.113341,5.276420,...,-8.807254,-9.599646,-9.835780,-9.484655,-9.392122,-10.324029,-10.021533,-10.808202,-11.090427,NaN

In [31]:
len(epochs)

360

In [32]:
trigger_indices

array([  2425,   4985,   7545,  10105,  12666,  15226,  17786,  20346,
        22906,  25466,  28026,  30586,  33146,  35706,  38266,  40827,
        43387,  45947,  48507,  51067,  53627,  56187,  58747,  61307,
        63867,  66427,  68987,  71548,  74108,  76668,  79228,  81788,
        84348,  86908,  89468,  92028,  94588,  97148,  99708, 102000,
       108000, 111000, 113000, 116000, 118000, 121000, 124000, 126000,
       129000, 131000, 134000, 136000, 139000, 141000, 144000, 147000,
       149000, 152000, 154000, 157000, 159000, 162000, 165000, 167000,
       170000, 172000, 175000, 177000, 180000, 182000, 185000, 188000,
       190000, 193000, 195000, 198000, 200000, 203000, 205000, 208000,
       214000, 216000, 219000, 221000, 224000, 227000, 229000, 232000,
       234000, 237000, 239000, 242000, 245000, 247000, 250000, 252000,
       255000, 257000, 260000, 262000, 265000, 268000, 270000, 273000,
       275000, 278000, 280000, 283000, 285000, 288000, 291000, 293000,
       296000, 298000, 301000, 303000, 306000, 309000, 311000, 314000,
       341000, 343000, 346000, 348000, 351000, 353000, 356000, 359000,
       361000, 364000, 366000, 369000, 371000, 374000, 377000, 379000,
       382000, 384000, 387000, 389000, 392000, 394000, 397000, 400000,
       402000, 405000, 407000, 410000, 412000, 415000, 417000, 420000,
       423000, 425000, 428000, 430000, 433000, 435000, 438000, 441000,
       446000, 448000, 451000, 453000, 456000, 459000, 461000, 464000,
       466000, 469000, 471000, 474000, 476000, 479000, 482000, 484000,
       487000, 489000, 492000, 494000, 497000, 499000, 502000, 505000,
       507000, 510000, 512000, 515000, 517000, 520000, 523000, 525000,
       528000, 530000, 533000, 535000, 538000, 540000, 543000, 546000,
       556000, 558000, 561000, 563000, 566000, 568000, 571000, 574000,
       576000, 579000, 581000, 584000, 586000, 589000, 591000, 594000,
       597000, 599000, 602000, 604000, 607000, 609000, 612000, 615000,
       617000, 620000, 622000, 625000, 627000, 630000, 632000, 635000,
       638000, 640000, 643000, 645000, 648000, 650000, 653000, 655000,
       665000, 668000, 671000, 673000, 676000, 678000, 681000, 683000,
       686000, 688000, 691000, 694000, 696000, 699000, 701000, 704000,
       706000, 709000, 711000, 714000, 717000, 719000, 722000, 724000,
       727000, 729000, 732000, 735000, 737000, 740000, 742000, 745000,
       747000, 750000, 752000, 755000, 758000, 760000, 763000, 765000,
       775000, 777000, 780000, 782000, 785000, 787000, 790000, 792000,
       795000, 798000, 800000, 803000, 805000, 808000, 810000, 813000,
       816000, 818000, 821000, 823000, 826000, 828000, 831000, 833000,
       836000, 839000, 841000, 844000, 846000, 849000, 851000, 854000,
       856000, 859000, 862000, 864000, 867000, 869000, 872000, 874000,
       880000, 883000, 885000, 888000, 890000, 893000, 895000, 898000,
       900000, 903000, 906000, 908000, 911000, 913000, 916000, 918000,
       921000, 924000, 926000, 929000, 931000, 934000, 936000, 939000,
       941000, 944000, 947000, 949000, 952000, 954000, 957000, 959000,
       962000, 964000, 967000, 970000, 972000, 975000, 977000, 980000])

NaN 값이 label인 부분 제거하기

In [34]:
# label이 NaN 값인 행 제거
eeg_d = eeg_d.dropna(subset=['label'])

In [35]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286,0.0
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928,0.0
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292,0.0
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115,0.0
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956995,3827.980,-0.629849,3.665406,2.482294,0.104257,3.751286,4.475523,2.724868,1.658097,-1.311275,...,1.449036,2.823937,1.605952,1.512523,1.240911,0.575283,-1.381152,-1.375000,-1.575607,3.0
956996,3827.984,1.284772,6.860541,4.423424,1.647884,4.809797,7.088760,4.489870,2.495641,-0.720632,...,1.556714,4.578716,3.326058,3.357318,2.327635,1.080533,0.868098,0.732344,0.367956,3.0
956997,3827.988,4.398806,10.537602,7.121385,4.240891,8.040082,10.235008,6.845332,4.819150,3.348238,...,3.449147,6.053240,5.639684,5.889438,4.751685,3.403172,3.048572,3.614002,3.589951,3.0
956998,3827.992,6.917575,13.269783,9.202669,6.737197,11.607995,12.370755,8.852902,7.511898,7.195227,...,4.657828,6.524579,6.840462,7.256925,6.344298,5.102419,4.036917,5.123222,5.550790,3.0
956999,3827.996,9.076520,14.586543,10.852980,9.262155,12.853571,13.118451,10.566836,10.249676,9.976559,...,4.940482,7.034133,7.464206,7.512285,6.672189,5.524717,5.002337,5.934630,6.317418,3.0

In [36]:
# 'label' 열에서 NaN 값을 가진 행 찾기
eeg_d[eeg_d['label'].isna()]

Empty DataFrame
Columns: [time, #  1, #  2, #  3, #  4, #  5, #  6, #  7, #  8, #  9, # 10, # 11, # 12, # 13, # 14, # 15, # 16, # 17, # 18, # 19, # 20, # 21, # 22, # 23, # 24, # 25, # 26, # 27, # 28, # 29, # 30, # 31, # 32, # 33, # 34, # 35, # 36, # 37, # 38, # 39, # 40, # 41, # 42, # 43, # 44, # 45, # 46, # 47, # 48, # 49, # 50, # 51, # 52, # 53, # 54, # 55, # 56, # 57, # 58, # 59, # 60, label]
Index: []

[0 rows x 62 columns]

In [37]:
trig_df

        index
0      2425.0
1      4985.0
2      7545.0
3     10105.0
4     12666.0
..        ...
355  970000.0
356  972000.0
357  975000.0
358  977000.0
359  980000.0

[360 rows x 1 columns]

In [38]:
# NaN 값이 있는 행 제거
trig_df.dropna(inplace=True)
label_df.dropna(inplace=True)

In [39]:
label_df

     label
0      3.0
1      4.0
4      3.0
5      3.0
6      3.0
..     ...
342    2.0
343    4.0
344    4.0
345    2.0
349    3.0

[180 rows x 1 columns]

In [40]:
# 동일한 인덱스를 trig_df에서도 제거
trig_df = trig_df.loc[label_df.index]

In [41]:
trig_df

        index
0      2425.0
1      4985.0
4     12666.0
5     15226.0
6     17786.0
..        ...
342  936000.0
343  939000.0
344  941000.0
345  944000.0
349  954000.0

[180 rows x 1 columns]

In [42]:
epochs[0]

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
3175,12.700,-3.348520,-0.250720,-2.482654,-1.851242,-2.175465,-0.987844,-1.392404,-0.524320,-0.083113,...,6.283760,4.919481,4.043227,4.352506,5.283337,5.994775,3.647183,3.511997,5.006592,3.0
3176,12.704,-3.615057,-0.941355,-3.589869,-2.098366,-4.178424,-3.049562,-3.090380,-1.478940,-0.667506,...,7.470905,5.362157,5.123103,5.829774,6.866582,7.578393,4.895352,5.547473,7.055971,3.0
3177,12.708,-3.428481,-1.134885,-4.175011,-2.005247,-3.297852,-3.190218,-3.645733,-2.190402,-1.164395,...,7.102110,5.530947,5.694640,6.371519,7.344365,7.590961,5.231593,6.639396,7.854992,3.0
3178,12.712,-2.926504,-0.781978,-3.947261,-1.704401,-1.107828,-2.090882,-3.358481,-2.673715,-1.867541,...,4.114056,4.871710,4.842830,4.875158,5.484756,5.034550,4.210133,5.494151,6.107945,3.0
3179,12.716,-3.219694,-1.427076,-4.115446,-2.574706,-0.473634,-1.879898,-4.105335,-4.270752,-3.961353,...,0.816430,3.180625,2.015370,1.242844,1.575828,1.201189,2.014375,2.137239,2.322316,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4170,16.680,-4.783375,-4.204794,-4.644526,-1.360577,-4.835431,-6.606673,-4.284070,-3.163033,-2.983199,...,-7.068261,-7.357605,-8.525092,-8.806878,-8.209372,-6.933076,-9.827940,-9.317529,-6.980871,3.0
4171,16.684,-5.933924,-6.003480,-5.972484,-2.549635,-8.106778,-9.064448,-6.109713,-4.558940,-4.298863,...,-9.948636,-11.325763,-13.124866,-14.009536,-12.963790,-10.645780,-13.957084,-14.271756,-11.211360,3.0
4172,16.688,-5.551888,-5.540527,-5.390845,-2.474424,-8.248217,-8.957105,-6.138438,-4.697029,-4.370740,...,-8.336164,-12.392643,-14.520735,-15.575106,-13.888911,-10.344139,-14.540412,-15.574646,-11.908883,3.0
4173,16.692,-5.951693,-5.286283,-5.310257,-3.470081,-7.650523,-8.857166,-6.636341,-5.798745,-5.445772,...,-5.590386,-11.580540,-13.943702,-14.768456,-12.600768,-8.478989,-12.861753,-14.332032,-10.613174,3.0
4174,16.696,-6.720207,-5.365971,-5.786780,-4.945659,-7.294645,-9.319849,-7.514054,-7.281707,-6.780186,...,-7.181322,-9.510474,-12.185127,-13.150381,-11.413335,-8.571995,-9.807562,-11.888534,-9.317466,3.0

feature calculation