In [9]:
import mne
import pandas as pd

In [10]:
# EEG 데이터 파일 경로
file_path = "C:/Users/windows/Desktop/4class_EEG-GPT/k3b.gdf"
eeg_d = mne.io.read_raw_gdf(file_path, preload=True)

Extracting EDF parameters from C:\Users\windows\Desktop\4class_EEG-GPT\k3b.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
#  1, #  2, #  3, #  4, #  5, #  6, #  7, #  8, #  9, # 10, # 11, # 12, # 13, # 14, # 15, # 16, # 17, # 18, # 19, # 20, # 21, # 22, # 23, # 24, # 25, # 26, # 27, # 28, # 29, # 30, # 31, # 32, # 33, # 34, # 35, # 36, # 37, # 38, # 39, # 40, # 41, # 42, # 43, # 44, # 45, # 46, # 47, # 48, # 49, # 50, # 51, # 52, # 53, # 54, # 55, # 56, # 57, # 58, # 59, # 60
Creating raw.info structure...
Reading 0 ... 986779  =      0.000 ...  3947.116 secs...

In [11]:
eeg_d

In [13]:
channel = eeg_d.ch_names
channel

['#  1',
 '#  2',
 '#  3',
 '#  4',
 '#  5',
 '#  6',
 '#  7',
 '#  8',
 '#  9',
 '# 10',
 '# 11',
 '# 12',
 '# 13',
 '# 14',
 '# 15',
 '# 16',
 '# 17',
 '# 18',
 '# 19',
 '# 20',
 '# 21',
 '# 22',
 '# 23',
 '# 24',
 '# 25',
 '# 26',
 '# 27',
 '# 28',
 '# 29',
 '# 30',
 '# 31',
 '# 32',
 '# 33',
 '# 34',
 '# 35',
 '# 36',
 '# 37',
 '# 38',
 '# 39',
 '# 40',
 '# 41',
 '# 42',
 '# 43',
 '# 44',
 '# 45',
 '# 46',
 '# 47',
 '# 48',
 '# 49',
 '# 50',
 '# 51',
 '# 52',
 '# 53',
 '# 54',
 '# 55',
 '# 56',
 '# 57',
 '# 58',
 '# 59',
 '# 60']

In [14]:
# 데이터를 DataFrame으로 변환
eeg_d = eeg_d.to_data_frame()


eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 51,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,7.517344,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,11.928453,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,12.015903,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.385745,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.538458,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,6.699425,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,9.901658,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,11.035943,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,8.793093,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,-0.646421,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197

HDR.TRIG / HDR.Classlabel 로드

In [17]:
trig_df = pd.read_csv('Trig.csv', header=None)
trig_df

            0
0      2425.0
1      4985.0
2      7545.0
3     10105.0
4     12666.0
..        ...
355  970000.0
356  972000.0
357  975000.0
358  977000.0
359  980000.0

[360 rows x 1 columns]

In [18]:
# trigger dataframe에 index 컬럼 이름 지정
trig_df.columns = ['index']
trig_df

        index
0      2425.0
1      4985.0
2      7545.0
3     10105.0
4     12666.0
..        ...
355  970000.0
356  972000.0
357  975000.0
358  977000.0
359  980000.0

[360 rows x 1 columns]

In [19]:
label_df = pd.read_csv('Classlabel.csv', header=None)
label_df

       0
0    3.0
1    4.0
2    NaN
3    NaN
4    3.0
..   ...
355  NaN
356  NaN
357  NaN
358  NaN
359  NaN

[360 rows x 1 columns]

In [20]:
# label dataframe에 label 컬럼 이름 지정
label_df.columns = ['label']
label_df

     label
0      3.0
1      4.0
2      NaN
3      NaN
4      3.0
..     ...
355    NaN
356    NaN
357    NaN
358    NaN
359    NaN

[360 rows x 1 columns]

In [21]:
# eeg_d에 label 열 추가
eeg_d['label'] = 0

In [22]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286,0
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928,0
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292,0
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115,0
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447,0
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015,0
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892,0
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595,0
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197,0

trig_df, label_df를 통해 eeg_d에 label 값 정하기

In [23]:
# 트리거 인덱스와 레이블 가져오기
trigger_indices = trig_df['index'].values
labels = label_df['label'].values

# 트리거 구간에 따라 레이블 지정
for i in range(len(trigger_indices) - 1):
    start_idx = trigger_indices[i]
    end_idx = trigger_indices[i + 1]
    label = labels[i]
    eeg_d.loc[start_idx:end_idx-1, 'label'] = label

# 마지막 트리거 이후 구간 레이블 지정
if len(trigger_indices) > 0:
    start_idx = trigger_indices[-1]
    label = labels[-1]
    eeg_d.loc[start_idx:, 'label'] = label

In [24]:
eeg_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,0.000,-0.079007,3.027897,3.435340,2.493118,5.307115,5.167698,5.699518,5.650690,6.598334,...,8.491150,10.667896,9.511298,7.631612,8.236697,8.996108,9.612918,7.882010,7.967286,0.0
1,0.004,4.043424,8.484671,8.330211,5.712888,14.085459,12.144965,10.694503,9.141956,9.526546,...,12.216795,15.419495,14.352876,12.500155,12.794380,13.118542,13.036466,11.741996,12.050928,0.0
2,0.008,5.509374,8.826194,8.848780,6.153412,13.277888,12.030220,10.579603,9.337083,9.707801,...,11.802236,15.454526,14.668870,13.521594,13.506372,13.420183,13.191850,12.655410,13.098292,0.0
3,0.012,5.789238,6.632859,7.745069,5.952848,6.242438,8.147380,8.511391,9.211001,10.432822,...,11.021574,11.766624,12.344253,13.010874,13.204244,13.183897,11.574326,12.312300,13.353115,0.0
4,0.016,3.106104,2.094402,4.073040,3.116299,-1.313143,2.091777,3.985583,6.503243,8.557767,...,8.579984,5.518208,7.376277,9.357081,9.995597,10.479179,7.333101,9.015664,10.694753,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986775,3947.100,-11.935436,-6.124911,-6.382433,-7.169771,-9.457293,-4.304360,-2.949946,-1.653053,-2.042546,...,3.093811,11.766624,14.138550,15.454691,12.513331,7.276752,17.300616,18.938029,13.655447,NaN
986776,3947.104,-4.534608,2.272753,1.564287,1.418668,2.797713,5.323159,5.262257,6.866479,7.323355,...,6.297220,17.374911,18.455303,18.528555,14.815593,9.672288,20.543306,20.811223,15.044015,NaN
986777,3947.108,1.649038,9.429550,7.941285,8.202031,15.130283,14.465786,12.204170,13.077512,13.970427,...,7.880080,20.658355,20.799154,19.924682,15.642347,10.969346,21.253998,20.999006,15.231892,NaN
986778,3947.112,2.364244,12.324904,9.076530,8.370361,22.594613,18.926055,14.151097,12.909403,12.070371,...,6.908290,20.222049,19.697297,18.120457,13.883446,10.197647,19.139754,18.796612,14.063595,NaN
986779,3947.116,-8.323867,-1.446050,-2.913627,-3.341147,1.100445,3.346575,1.199243,1.006674,-0.201867,...,0.234971,5.906743,6.738794,6.560056,4.369927,3.081421,7.399330,8.477816,6.585197,NaN

In [25]:
eeg_d[2500:3100]

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
2500,10.000,5.553797,3.509824,5.281866,2.571911,6.361064,4.072063,5.147356,5.437551,6.679586,...,5.578472,4.731583,6.051850,6.366746,6.906397,6.590517,7.353479,7.163334,7.705985,3.0
2501,10.004,7.512840,6.636654,7.166935,3.703665,10.362419,7.229415,7.183651,6.464218,5.732683,...,4.706283,3.658333,5.252248,5.982513,6.484823,5.959584,6.023798,6.792405,7.289199,3.0
2502,10.008,8.179181,7.885109,8.102461,4.061816,11.297742,8.210305,8.310315,7.289754,4.926410,...,4.114056,2.744319,3.936064,4.901410,5.362968,5.127556,4.003803,5.452422,5.786177,3.0
2503,10.012,8.045913,8.108996,8.449342,4.108375,10.531234,7.677293,8.827368,8.223360,5.404549,...,3.007669,0.530940,1.405364,2.209392,2.859287,3.335303,0.228730,1.988867,2.933459,3.0
2504,10.016,8.316892,8.955213,9.325303,4.638437,11.060489,7.840158,9.746573,9.538214,7.404608,...,2.396599,-1.676069,-0.938487,-0.730825,0.247870,1.354524,-3.375674,-1.980079,-0.262622,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,12.380,1.498001,0.542371,0.362468,-1.245969,2.514835,0.274357,-1.631780,-2.202409,-3.526965,...,-5.127372,1.027756,0.820088,-1.033916,-2.375257,-3.139935,2.070416,1.585481,-1.221447,3.0
3096,12.384,1.786749,0.231206,0.905564,-1.020334,2.341458,0.570474,-1.063661,-1.316834,-3.439463,...,-5.127372,1.944955,2.713305,1.619917,-0.576541,-2.524083,3.794926,4.015070,0.193035,3.0
3097,12.388,5.185088,3.851346,4.738770,2.571911,6.297188,4.582866,3.174896,2.933926,0.535655,...,-3.073422,2.266611,3.545880,3.638930,1.536013,-0.658933,3.708318,4.794022,1.408842,3.0
3098,12.392,10.089359,9.543391,10.050599,7.632572,12.328878,10.612557,9.149728,9.075914,7.254603,...,-0.752970,1.900369,3.471690,4.378758,2.931891,1.274086,2.646101,3.968704,2.093408,3.0
3099,12.396,14.189578,14.552391,14.910432,11.969770,16.882302,15.572525,14.237272,14.602502,13.707919,...,4.127516,1.518203,3.337049,4.641277,4.590082,4.531814,2.001639,3.022833,3.315693,3.0

In [26]:
print(eeg_d['label'].value_counts())  # 각 레이블의 개수 출력

label
1.0    126921
2.0    125360
4.0    125241
3.0    124652
0.0      2425
Name: count, dtype: int64

epoch 자르기

In [30]:
# 샘플링 주파수
fs = 250
start_offset = 3 * fs
end_offset = 7 * fs

# Epochs를 저장할 리스트 초기화
epochs = []

trigger_indices = trig_df['index'].values.astype(int)  # 정수로 변환
labels = label_df['label'].values

# Epoch 추출
for idx, label in zip(trigger_indices, labels):
    start_idx = int(idx + start_offset)  # 정수로 변환
    end_idx = int(idx + end_offset)  # 정수로 변환
    
    if end_idx <= len(eeg_d):
        epoch = eeg_d.iloc[start_idx:end_idx].copy()
        epoch['label'] = label
        epochs.append(epoch)

# epochs 리스트를 단일 DataFrame으로 결합
epochs_d = pd.concat(epochs, ignore_index=True)

In [31]:
epochs_d

,time,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,12.700,-3.348520,-0.250720,-2.482654,-1.851242,-2.175465,-0.987844,-1.392404,-0.524320,-0.083113,...,6.283760,4.919481,4.043227,4.352506,5.283337,5.994775,3.647183,3.511997,5.006592,3.0
1,12.704,-3.615057,-0.941355,-3.589869,-2.098366,-4.178424,-3.049562,-3.090380,-1.478940,-0.667506,...,7.470905,5.362157,5.123103,5.829774,6.866582,7.578393,4.895352,5.547473,7.055971,3.0
2,12.708,-3.428481,-1.134885,-4.175011,-2.005247,-3.297852,-3.190218,-3.645733,-2.190402,-1.164395,...,7.102110,5.530947,5.694640,6.371519,7.344365,7.590961,5.231593,6.639396,7.854992,3.0
3,12.712,-2.926504,-0.781978,-3.947261,-1.704401,-1.107828,-2.090882,-3.358481,-2.673715,-1.867541,...,4.114056,4.871710,4.842830,4.875158,5.484756,5.034550,4.210133,5.494151,6.107945,3.0
4,12.716,-3.219694,-1.427076,-4.115446,-2.574706,-0.473634,-1.879898,-4.105335,-4.270752,-3.961353,...,0.816430,3.180625,2.015370,1.242844,1.575828,1.201189,2.014375,2.137239,2.322316,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359995,3926.980,18.494142,17.895518,17.173916,16.152963,11.457431,14.613845,14.783050,13.870026,10.645329,...,-0.483776,2.046866,2.122533,3.660409,1.650775,-0.296963,0.310243,0.590927,-0.685887,NaN
359996,3926.984,17.272516,15.736336,15.555139,15.447407,10.184480,13.225794,13.567019,12.519149,10.392196,...,-3.321081,-0.777979,-1.012677,0.116397,-1.501662,-3.569774,-2.677719,-2.698755,-4.108717,NaN
359997,3926.988,15.522260,13.413982,12.625925,12.739792,8.952592,10.701393,10.633861,8.913808,7.604614,...,-6.605247,-4.946774,-5.013436,-4.422803,-5.424642,-7.337779,-6.531757,-6.686247,-7.820922,NaN
359998,3926.992,15.357896,12.674016,10.558657,10.551495,9.500098,9.061642,8.546500,6.149013,5.670182,...,-8.363084,-7.873529,-7.868374,-7.451323,-7.961112,-9.479433,-8.859973,-9.243343,-10.043062,NaN
359999,3926.996,15.633317,11.546991,9.101057,9.047265,9.559411,7.954903,7.537928,5.113341,5.276420,...,-8.807254,-9.599646,-9.835780,-9.484655,-9.392122,-10.324029,-10.021533,-10.808202,-11.090427,NaN

time 열 제거

In [33]:
new_eeg_d = epochs_d.iloc[:,1:]
new_eeg_d

,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,# 10,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,-3.348520,-0.250720,-2.482654,-1.851242,-2.175465,-0.987844,-1.392404,-0.524320,-0.083113,1.920120,...,6.283760,4.919481,4.043227,4.352506,5.283337,5.994775,3.647183,3.511997,5.006592,3.0
1,-3.615057,-0.941355,-3.589869,-2.098366,-4.178424,-3.049562,-3.090380,-1.478940,-0.667506,-1.347319,...,7.470905,5.362157,5.123103,5.829774,6.866582,7.578393,4.895352,5.547473,7.055971,3.0
2,-3.428481,-1.134885,-4.175011,-2.005247,-3.297852,-3.190218,-3.645733,-2.190402,-1.164395,-2.151130,...,7.102110,5.530947,5.694640,6.371519,7.344365,7.590961,5.231593,6.639396,7.854992,3.0
3,-2.926504,-0.781978,-3.947261,-1.704401,-1.107828,-2.090882,-3.358481,-2.673715,-1.867541,0.213327,...,4.114056,4.871710,4.842830,4.875158,5.484756,5.034550,4.210133,5.494151,6.107945,3.0
4,-3.219694,-1.427076,-4.115446,-2.574706,-0.473634,-1.879898,-4.105335,-4.270752,-3.961353,-0.042431,...,0.816430,3.180625,2.015370,1.242844,1.575828,1.201189,2.014375,2.137239,2.322316,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359995,18.494142,17.895518,17.173916,16.152963,11.457431,14.613845,14.783050,13.870026,10.645329,9.034369,...,-0.483776,2.046866,2.122533,3.660409,1.650775,-0.296963,0.310243,0.590927,-0.685887,NaN
359996,17.272516,15.736336,15.555139,15.447407,10.184480,13.225794,13.567019,12.519149,10.392196,9.154419,...,-3.321081,-0.777979,-1.012677,0.116397,-1.501662,-3.569774,-2.677719,-2.698755,-4.108717,NaN
359997,15.522260,13.413982,12.625925,12.739792,8.952592,10.701393,10.633861,8.913808,7.604614,6.988305,...,-6.605247,-4.946774,-5.013436,-4.422803,-5.424642,-7.337779,-6.531757,-6.686247,-7.820922,NaN
359998,15.357896,12.674016,10.558657,10.551495,9.500098,9.061642,8.546500,6.149013,5.670182,3.940087,...,-8.363084,-7.873529,-7.868374,-7.451323,-7.961112,-9.479433,-8.859973,-9.243343,-10.043062,NaN
359999,15.633317,11.546991,9.101057,9.047265,9.559411,7.954903,7.537928,5.113341,5.276420,-0.089407,...,-8.807254,-9.599646,-9.835780,-9.484655,-9.392122,-10.324029,-10.021533,-10.808202,-11.090427,NaN

label 값이 NaN인 행만 가져오기

In [36]:
# label이 NaN인 행만 가져오기
only_nan_eeg_d = new_eeg_d[new_eeg_d['label'].isna()]
only_nan_eeg_d

,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,# 10,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
2000,9.209789,9.645848,8.740161,9.537931,7.059134,8.424990,9.002911,7.370806,8.035877,4.947460,...,2.361604,6.323941,6.733298,4.156809,3.147362,1.945238,5.440470,3.129476,0.689723,NaN
2001,9.778400,10.746310,9.437426,10.941879,8.765527,10.049934,10.471085,8.907804,8.592143,5.391122,...,2.657717,6.301648,6.988841,4.956300,3.697751,2.716938,6.118047,4.337315,2.255371,NaN
2002,10.076032,11.323104,10.190753,11.754880,9.700850,11.278822,11.693500,10.399773,9.242162,5.500733,...,2.221623,6.136043,7.068527,5.292803,4.107614,2.857704,6.393153,4.775475,3.302736,NaN
2003,9.831707,10.833588,10.383464,11.504175,9.472722,11.082644,11.572216,10.612911,8.698396,5.521611,...,1.893206,6.234769,7.263619,5.607826,4.672055,2.852676,6.775246,5.197408,4.121192,NaN
2004,7.388456,7.987566,8.102461,8.671207,7.223386,8.276931,8.613525,7.779071,6.167071,4.086234,...,0.837966,5.234768,5.983156,4.452740,3.838275,1.817041,5.687556,4.351225,3.630982,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359995,18.494142,17.895518,17.173916,16.152963,11.457431,14.613845,14.783050,13.870026,10.645329,9.034369,...,-0.483776,2.046866,2.122533,3.660409,1.650775,-0.296963,0.310243,0.590927,-0.685887,NaN
359996,17.272516,15.736336,15.555139,15.447407,10.184480,13.225794,13.567019,12.519149,10.392196,9.154419,...,-3.321081,-0.777979,-1.012677,0.116397,-1.501662,-3.569774,-2.677719,-2.698755,-4.108717,NaN
359997,15.522260,13.413982,12.625925,12.739792,8.952592,10.701393,10.633861,8.913808,7.604614,6.988305,...,-6.605247,-4.946774,-5.013436,-4.422803,-5.424642,-7.337779,-6.531757,-6.686247,-7.820922,NaN
359998,15.357896,12.674016,10.558657,10.551495,9.500098,9.061642,8.546500,6.149013,5.670182,3.940087,...,-8.363084,-7.873529,-7.868374,-7.451323,-7.961112,-9.479433,-8.859973,-9.243343,-10.043062,NaN
359999,15.633317,11.546991,9.101057,9.047265,9.559411,7.954903,7.537928,5.113341,5.276420,-0.089407,...,-8.807254,-9.599646,-9.835780,-9.484655,-9.392122,-10.324029,-10.021533,-10.808202,-11.090427,NaN

In [37]:
print(only_nan_eeg_d['label'].value_counts())

Series([], Name: count, dtype: int64)

In [38]:
# 인덱스를 0부터 시작하도록 재설정
only_nan_eeg_d.reset_index(drop=True, inplace=True)
only_nan_eeg_d

,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,# 10,...,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60,label
0,9.209789,9.645848,8.740161,9.537931,7.059134,8.424990,9.002911,7.370806,8.035877,4.947460,...,2.361604,6.323941,6.733298,4.156809,3.147362,1.945238,5.440470,3.129476,0.689723,NaN
1,9.778400,10.746310,9.437426,10.941879,8.765527,10.049934,10.471085,8.907804,8.592143,5.391122,...,2.657717,6.301648,6.988841,4.956300,3.697751,2.716938,6.118047,4.337315,2.255371,NaN
2,10.076032,11.323104,10.190753,11.754880,9.700850,11.278822,11.693500,10.399773,9.242162,5.500733,...,2.221623,6.136043,7.068527,5.292803,4.107614,2.857704,6.393153,4.775475,3.302736,NaN
3,9.831707,10.833588,10.383464,11.504175,9.472722,11.082644,11.572216,10.612911,8.698396,5.521611,...,1.893206,6.234769,7.263619,5.607826,4.672055,2.852676,6.775246,5.197408,4.121192,NaN
4,7.388456,7.987566,8.102461,8.671207,7.223386,8.276931,8.613525,7.779071,6.167071,4.086234,...,0.837966,5.234768,5.983156,4.452740,3.838275,1.817041,5.687556,4.351225,3.630982,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179995,18.494142,17.895518,17.173916,16.152963,11.457431,14.613845,14.783050,13.870026,10.645329,9.034369,...,-0.483776,2.046866,2.122533,3.660409,1.650775,-0.296963,0.310243,0.590927,-0.685887,NaN
179996,17.272516,15.736336,15.555139,15.447407,10.184480,13.225794,13.567019,12.519149,10.392196,9.154419,...,-3.321081,-0.777979,-1.012677,0.116397,-1.501662,-3.569774,-2.677719,-2.698755,-4.108717,NaN
179997,15.522260,13.413982,12.625925,12.739792,8.952592,10.701393,10.633861,8.913808,7.604614,6.988305,...,-6.605247,-4.946774,-5.013436,-4.422803,-5.424642,-7.337779,-6.531757,-6.686247,-7.820922,NaN
179998,15.357896,12.674016,10.558657,10.551495,9.500098,9.061642,8.546500,6.149013,5.670182,3.940087,...,-8.363084,-7.873529,-7.868374,-7.451323,-7.961112,-9.479433,-8.859973,-9.243343,-10.043062,NaN
179999,15.633317,11.546991,9.101057,9.047265,9.559411,7.954903,7.537928,5.113341,5.276420,-0.089407,...,-8.807254,-9.599646,-9.835780,-9.484655,-9.392122,-10.324029,-10.021533,-10.808202,-11.090427,NaN

In [39]:
# 마지막 열(label) 제거
my_x_test = only_nan_eeg_d.iloc[:, :-1]
my_x_test

,# 1,# 2,# 3,# 4,# 5,# 6,# 7,# 8,# 9,# 10,...,# 51,# 52,# 53,# 54,# 55,# 56,# 57,# 58,# 59,# 60
0,9.209789,9.645848,8.740161,9.537931,7.059134,8.424990,9.002911,7.370806,8.035877,4.947460,...,3.139673,2.361604,6.323941,6.733298,4.156809,3.147362,1.945238,5.440470,3.129476,0.689723
1,9.778400,10.746310,9.437426,10.941879,8.765527,10.049934,10.471085,8.907804,8.592143,5.391122,...,3.322290,2.657717,6.301648,6.988841,4.956300,3.697751,2.716938,6.118047,4.337315,2.255371
2,10.076032,11.323104,10.190753,11.754880,9.700850,11.278822,11.693500,10.399773,9.242162,5.500733,...,3.080515,2.221623,6.136043,7.068527,5.292803,4.107614,2.857704,6.393153,4.775475,3.302736
3,9.831707,10.833588,10.383464,11.504175,9.472722,11.082644,11.572216,10.612911,8.698396,5.521611,...,2.993065,1.893206,6.234769,7.263619,5.607826,4.672055,2.852676,6.775246,5.197408,4.121192
4,7.388456,7.987566,8.102461,8.671207,7.223386,8.276931,8.613525,7.779071,6.167071,4.086234,...,1.858780,0.837966,5.234768,5.983156,4.452740,3.838275,1.817041,5.687556,4.351225,3.630982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179995,18.494142,17.895518,17.173916,16.152963,11.457431,14.613845,14.783050,13.870026,10.645329,9.034369,...,2.275456,-0.483776,2.046866,2.122533,3.660409,1.650775,-0.296963,0.310243,0.590927,-0.685887
179996,17.272516,15.736336,15.555139,15.447407,10.184480,13.225794,13.567019,12.519149,10.392196,9.154419,...,-0.901056,-3.321081,-0.777979,-1.012677,0.116397,-1.501662,-3.569774,-2.677719,-2.698755,-4.108717
179997,15.522260,13.413982,12.625925,12.739792,8.952592,10.701393,10.633861,8.913808,7.604614,6.988305,...,-4.550831,-6.605247,-4.946774,-5.013436,-4.422803,-5.424642,-7.337779,-6.531757,-6.686247,-7.820922
179998,15.357896,12.674016,10.558657,10.551495,9.500098,9.061642,8.546500,6.149013,5.670182,3.940087,...,-6.693369,-8.363084,-7.873529,-7.868374,-7.451323,-7.961112,-9.479433,-8.859973,-9.243343,-10.043062
179999,15.633317,11.546991,9.101057,9.047265,9.559411,7.954903,7.537928,5.113341,5.276420,-0.089407,...,-7.485568,-8.807254,-9.599646,-9.835780,-9.484655,-9.392122,-10.324029,-10.021533,-10.808202,-11.090427

In [40]:
# CSV 파일로 저장
csv_file_path = "X_test.csv"
my_x_test.to_csv(csv_file_path, index=False)

print("CSV 파일이 저장되었습니다:", csv_file_path)

CSV 파일이 저장되었습니다: X_test.csv